import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Project } from '../types';
import { compileProject } from '../core/compiler';
import { generateDocumentation } from '../core/documentationGenerator';

export async function exportProjectAsZip(project: Project): Promise<void> {
  const zip = new JSZip();
  const activePage = project.pages.find(p => p.id === project.activePageId) || project.pages[0];
  const compiled = compileProject(activePage.rootComponent, project.designSystem, activePage.seoTitle || project.name);

  // Standalone HTML that links to styles/style.css and scripts/app.js
  const standaloneHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${activePage.seoTitle || project.name}</title>
  <meta name="description" content="${activePage.seoDescription || 'Generated with Sketch2Web'}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="./styles/style.css">
</head>
<body>
${compiled.html.replace('<!-- Semantic HTML5 Body -->\n', '')}

  <script src="./scripts/app.js"></script>
</body>
</html>`;

  // Root files
  zip.file('index.html', standaloneHtml);
  zip.file('standalone.html', compiled.fullDocument);
  zip.file('DOCUMENTATION.md', generateDocumentation(project));

  // Styles folder
  const stylesFolder = zip.folder('styles');
  stylesFolder?.file('style.css', compiled.css);

  // Scripts folder
  const scriptsFolder = zip.folder('scripts');
  scriptsFolder?.file('app.js', compiled.js);

  // README
  const readmeContent = `# ${project.name}
Generated by **Sketch2Web — AI-Powered Visual Web Development Platform**

## Getting Started

1. Double-click \`index.html\` to view the website directly in any web browser.
2. No build tools, Node.js, or local servers are required.

## Project Structure
- \`index.html\`: Semantic HTML5 structure
- \`styles/style.css\`: Scoped CSS3 styles with CSS variables and responsive media queries
- \`scripts/app.js\`: Interactive vanilla JavaScript ES6
- \`DOCUMENTATION.md\`: Component hierarchy and design token specifications

---
*Built with Sketch2Web — "From your sketch to a working website."*
`;
  zip.file('README.md', readmeContent);

  // Generate and trigger download
  const blob = await zip.generateAsync({ type: 'blob' });
  const filename = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}-sketch2web.zip`;
  saveAs(blob, filename);
}

export function downloadSingleFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  saveAs(blob, filename);
}
